name: CI

on: push

jobs:
  build_and_test:
    name: "Build and test"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install dependencies (linux)
      run: sudo apt install ninja-build
      if: matrix.os == 'ubuntu-latest'
      
    - name: Install Chocolatey (windows)
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; 
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; 
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      shell: powershell
      if: matrix.os == 'windows-latest'
      
    - name: Install Ninja (windows)
      run: choco install ninja -y
      shell: powershell
      if: matrix.os == 'windows-latest'
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.2'
        
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v3

    - name: Build
      run: cmake -S . -B build -G "Ninja Multi-Config" && cmake --build build --config Debug
