name: CI

on: push

jobs:
  build_and_test:
    name: "Build and test"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install dependencies (linux)
      run: sudo apt install ninja-build
      if: matrix.os == 'ubuntu-latest'

    - name: Download and extract Python archive (windows)
      run: |
        $pythonArchiveUrl = "https://github.com/actions/python-versions/releases/download/3.11.9-9667582339/python-3.11.9-win32-x64.zip"
        $downloadPath = "$env:TEMP\python-archive.zip"
        Invoke-WebRequest -Uri $pythonArchiveUrl -OutFile $downloadPath
        Expand-Archive -Path $downloadPath -DestinationPath "$env:TEMP\python-3.11.9" -Force
      shell: pwsh
      if: matrix.os == 'windows-latest'

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.2'

    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v3

    - name: Build
      run: cmake -S . -B build -G "Ninja Multi-Config" && cmake --build build --config Debug
      shell: pwsh
      if: matrix.os == 'windows-latest'
